*[custom]
;专为RULE-SET设计

;设置规则标志位
ruleset=🌎 全球直连,[]RULE-SET,pt
ruleset=🌎 全球直连,[]RULE-SET,tracker
ruleset=🌎 全球直连,[]RULE-SET,applications
ruleset=🌎 全球直连,[]DOMAIN,clash.razord.top
ruleset=🌎 全球直连,[]DOMAIN,yacd.haishan.me
ruleset=🌎 全球直连,[]RULE-SET,private
ruleset=🛑 广告拦截,[]RULE-SET,reject
ruleset=🌎 全球直连,[]RULE-SET,icloud
ruleset=🌎 全球直连,[]RULE-SET,apple
ruleset=🌎 全球直连,[]RULE-SET,google
ruleset=🎯 今日晴,[]RULE-SET,proxy
ruleset=🌎 全球直连,[]RULE-SET,direct
ruleset=🌎 全球直连,[]RULE-SET,lancidr
ruleset=🌎 全球直连,[]RULE-SET,cncidr
ruleset=🎯 今日晴,[]RULE-SET,telegramcidr
ruleset=🌎 全球直连,[]GEOIP,LAN
ruleset=🌎 全球直连,[]GEOIP,CN
ruleset=🐋 漏网之鱼,[]MATCH
;设置规则标志位

;设置分组标志位
custom_proxy_group=🎯 今日晴`select`[]♻️ 自动选择`[]🚀 手动切换`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌎 全球直连`select`[]DIRECT`[]🎯 今日晴
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇨🇳 台湾节点`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🐋 漏网之鱼`select`[]🎯 今日晴`[]🌎 全球直连
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

clash_rule_base=https://raw.githubusercontent.com/Qoo-330ml/Clash_Rules_PT/main/base.yml
